MAINTAINERS.md
correcting contact detail for khaines
=> Updating MAINTAINERS details

.gitignore, Chart.yaml, tools/chart-version-tag.sh
- updated chart yaml to point at cortex team and repository.
- added version tag script similar to the one used in cortex for container tags. This is to assist with CI/CD pipelines when packaging the chart, which will override what is in the chart.yaml.
=> Updating chart.yaml and adding versioning script for CI/CD pipeline

tools/chart-version-tag.sh
=> removing redundant lines from versioning script

templates/alertmanager-dep.yaml, templates/configs-dep.yaml, templates/distributor-dep.yaml, templates/ingester-dep.yaml, templates/querier-dep.yaml, templates/query-frontend-dep.yaml, templates/ruler-dep.yaml, templates/table-manager-dep.yaml
Fixes the syntax issue when trying to deploy the helm chart.
Fixes cortexproject/cortex-helm-chart#38
=> Fixing config template for Issue# 38

templates/ingester-statefulset.yaml, values.yaml
=> adding option to deploy ingester as statefulset

templates/compactor-statefulset.yaml, templates/store-gateway-statefulset.yaml, templates/store-gateway-svc.yaml, templates/table-manager-dep.yaml, values.yaml
Add extra components and options for utilizing the newer blocks storage mode of Cortex.
Resolves #49
=> Blocks storage support in Cortex Helm chart

templates/alertmanager-dep.yaml, templates/alertmanager-statefulset.yaml, templates/alertmanager-svc-headless.yaml, values.yaml
=> adding ability to run alertmanager as statefulset 

templates/configs-svc.yaml, templates/distributor-svc.yaml, templates/ingester-svc.yaml, templates/nginx-svc.yaml, templates/querier-svc.yaml, templates/query-frontend-svc-headless.yaml, templates/query-frontend-svc.yaml, templates/ruler-dep.yaml, templates/ruler-svc.yaml, templates/store-gateway-svc.yaml, templates/table-manager-svc.yaml, values.yaml
=> fix service ports, fix ruler endpoint for configs and alertmanager

templates/nginx-config.yaml, templates/querier-dep.yaml
Signed-off-by: 하광일/TC_Core Engineering <kwangil_ha@yanolja.com>
=> Fix grpc port for querier

CHANGELOG.md, templates/compactor-svc.yaml
=> avoid creating compactor service if not enabled

Chart.yaml, templates/alertmanager-statefulset.yaml
This fixes issues [86](https://github.com/cortexproject/cortex-helm-chart/issues/86)
=> fix: alertmanager cluster peers not reachable due to wrong dns name

README.md
Minor fix, seems like incorrect spacing caused the format break
=> doc: fix header

templates/ingester-statefulset.yaml
=> correct reference to now headless service in ingester statefulset

CHANGELOG.md, templates/ingress.yaml
Update apiVersion: networking.k8s.io/v1beta1 -> networking.k8s.io/v1 for Kubernetes versions 1.19+
=> Update ingress.yaml 

CHANGELOG.md, Chart.yaml, templates/_helpers.tpl, templates/compactor-statefulset.yaml, templates/ingester-dep.yaml, templates/ingester-statefulset.yaml, templates/querier-dep.yaml, templates/ruler-dep.yaml, templates/store-gateway-statefulset.yaml, values.yaml
Based on changes picked from #85, this unifies the cache settings into a template function and adds in support for Memcached instances when using blocks storage.
=> Unified memcache settings into template function + add blocks cache

CHANGELOG.md, values.yaml
=> Update replication factor to match what documentation say is default

.github/stale.yml
Adding the stalebot config used in the main cortex repo.
=> Aligning git automation tool configuration with main cortex repo.

.github/workflows/lint-test.yml, .helmignore, ct.yaml
=> adding initial lint test for chart updates

.github/pull_request_template.md
added tiny pr template so people actually know what to do
Signed-off-by: ShuzZzle <niclas.schad@gmail.com>
=> created pr template

CHANGELOG.md, templates/_helpers.tpl, templates/distributor/distributor-svc-headless.yaml, templates/distributor/distributor-svc.yaml, templates/ingester/ingester-svc-headless.yaml, templates/nginx/nginx-svc.yaml, templates/querier/querier-svc.yaml, templates/query-frontend/query-frontend-svc.yaml, templates/ruler/ruler-svc.yaml, templates/store-gateway/store-gateway-svc.yaml, templates/table-manager/table-manager-svc.yaml
- Label Fix for Services(Credit: @kwangil-ha)
-  Removed dnssrvnoa resolution from block memcached (probably oversight) and moved back to simple dns resolution
**Checklist**
=> fix service labels and change dns resolution for memcached blocks index

CHANGELOG.md, templates/query-frontend/query-frontend-dep.yaml
Signed-off-by: Oliver Edelmann <oliver.edelmann@daimler.com>
Fix querier-frontend memcached args
Fixes #170
=> Fix memcached args

.github/stale.yml, .github/workflows/lint-test.yml
Signed-off-by: ShuzZzle <niclas.schad@gmail.com>
Update kind Cluster from 1.1.0 -> 1.2.0
Set Stale Config to 30D and fix Labels
N.A
**Checklist**
- N.A.
=> update kind cluster and stale config

README.md
Signed-off-by: Raphael Grömmer <r.groemmer@yahoo.de>
I had a little bit of struggle configuring the sidecar for the `alertManager` & `ruler` with the actual documentation, after successfully accomplish the configuration I have some changes for the `README.md`.
- Updated the storage configuration example
- Added a example `ConfigMap` containing a `alertmanager-config`
- Added some missing helm values to the values table.
**Checklist**
- [ x] `README.md` updated`
=> Updated Readme for AlertManager & Ruler sidecar configuration

README.md.gotmpl
Signed-off-by: ShuzZzle <niclas.schad@gmail.com>
Triggerhappy me forgot to update the changes in #181 also in the template. This pr should fix that
Persist #181
=> update docs also in the tmpl file

CHANGELOG.md, templates/nginx/nginx-config.yaml
**What this PR does**: Corrects bug in nginx config for auth orgs
**Which issue(s) this PR fixes**: None
**Checklist**
=> [BUGFIX] Correcting nginx config for auth orgs to right proxy_pass

README.md, ci/test-values.yaml, values.yaml
exercise memcached features in chart test
=> exercise memcached in test

README.md, README.md.gotmpl
Clarifies kv store dependency based on language from the docs: https://cortexmetrics.io/docs/guides/getting-started-with-gossiped-ring/
**Checklist**
=> clarify kv store dependency

CHANGELOG.md, README.md, templates/alertmanager/alertmanager-dep.yaml, templates/alertmanager/alertmanager-statefulset.yaml, templates/compactor/compactor-statefulset.yaml, templates/configs/configs-dep.yaml, templates/distributor/distributor-dep.yaml, templates/ingester/ingester-dep.yaml, templates/ingester/ingester-statefulset.yaml, templates/querier/querier-dep.yaml, templates/query-frontend/query-frontend-dep.yaml, templates/ruler/ruler-dep.yaml, templates/runtime-configmap.yaml, templates/store-gateway/store-gateway-statefulset.yaml, templates/table-manager/table-manager-dep.yaml, values.yaml
Creates and mounts a configmap for [runtime configuration](https://cortexmetrics.io/docs/configuration/arguments/#runtime-configuration-file).
**Checklist**
=> support runtime configuration

renovate.json
add "dependencies" pr label to renovate PR's
**Checklist**
=> add pr label

CHANGELOG.md, README.md, ci/test-values.yaml, templates/nginx/nginx-dep.yaml, templates/nginx/nginx-hpa.yaml, values.yaml
Adds a HorizontalPodAutoscaler for the nginx.
Pure copy of #190 #189 and #182 but for nginx
**Checklist**
=> add autoscaler for nginx

CHANGELOG.md, README.md, templates/distributor/distributor-dep.yaml, templates/querier/querier-dep.yaml, templates/query-frontend/query-frontend-dep.yaml, values.yaml
Signed-off-by: brian <puttbrian@gmail.com>
**What this PR does**: Adds in lifecycle as an option for querier, querier-frontend, and distributor
Fixes #243
**Checklist**
- [ x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`
=> add lifecycle to querier, distributor, query-frontend

renovate.json
GNARRR. A wild comma appeared. Be Gone!
**Checklist**
=> remove comma

docs/guides/configure_memcached.markdown, docs/guides/configure_rules_via_configmap.markdown, docs/guides/configure_rules_via_sidecar.markdown, docs/guides/getting_started_with_block_storage.markdown, docs/guides/memberlist.markdown, docs/guides/upgrade-v1.markdown
Adds a guide to assist in upgrading from chart version v0.6.0 to v1.0.0.
**Checklist**
This PR doesn't change the chart.
=> add upgrade guide

.github/workflows/renovate-config-validator.yml
Validates renovate config before merging the pr
**Checklist**
=> add stage to validate renovate config

renovate.json
Relict from #302. Forgot to update renovate
**Checklist**
=> update sidecar in renovate

CHANGELOG.md, docs/guides/configure_memcached.markdown
Signed-off-by: Jiacheng Xu <jiachengxu@users.noreply.github.com>
This PR fixes the indentation of memcached configuration in the memcached guide.
**Checklist**
=> Fix the indentation of memcached guide

Chart.yaml, MAINTAINERS.md, README.md, docs/index.yaml
=> update maintainer info

docs/guides/configure_rules_via_sidecar.markdown
Clarify sidecar docs
**Checklist**
=> update sidecar docs

renovate.json
fixxes renovate assignee config
**Checklist**
=> fix renovate assignee

README.md, README.md.gotmpl
=> update consul chart link to current

CHANGELOG.md, README.md, docs/_config.yml, docs/development.md, docs/development/developing_the_docs.md, docs/guides.md, docs/guides/configure_configmap.markdown, docs/guides/configure_memberlist.markdown, docs/guides/configure_memcached.markdown, docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown, docs/guides/configure_rules_via_configmap.markdown, docs/guides/configure_rules_via_sidecar.markdown, docs/guides/getting_started_with_block_storage.markdown, docs/guides/upgrade-v1.markdown, templates/ruler/ruler-dep.yaml, values.yaml
Rework documentation and ruler volumes (remove duplicates)
**Checklist**
=> rework docs and ruler volumes

CHANGELOG.md, templates/distributor/distributor-hpa.yaml
**What this PR does**: Simple 1 character typo fix introduced in #319, should be `enabled` not `enable` for the key.
**Checklist**
=> Fix typo introduced in #319

Makefile, README.md
readme.md update and pin version helm-docs to v1.8.1
@kd7lxl Apparently helm-docs changed the way they build the maintainer table so this is now necessary
**Checklist**
=> update README with new format and pin helm-docs to latest version

CHANGELOG.md, templates/query-scheduler/query-scheduler-dep.yaml
This uses the established pattern of using the helper function for defining the volume containing the Cortex config which should be mounted.
Fixes #354 
**Checklist**
=> Fix mounting cortex config when using configmap

renovate.json
teach renovate to bump the damn badge
**Checklist**
=> bump cortex badge in README.md via renovate

CHANGELOG.md, Chart.lock, Chart.yaml, README.md
Updates memcached to 6.3.12, to correctly apply securityContext configuration to metrics exporters.
Fixes #440
**Checklist**
=> Update memcached to v6.3.12

CHANGELOG.md, templates/store-gateway/store-gateway-statefulset.yaml
=> Replicas control in store gateway

CHANGELOG.md, templates/svc-memberlist-headless.yaml
Adds the `appProtocol` field to `templates/svc-memberlist-headless.yaml`. This makes the service compliant to the [Istio specification](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection)
**Checklist**
=> Add app protocol field

CHANGELOG.md, Chart.yaml, README.md
Update cortex to v1.16.0
**Checklist**
=> bump cortex to 1.16.0

CHANGELOG.md, Chart.yaml, README.md
Update cortex to v1.17.1
Fixes #498 
**Checklist**
=> Bump Cortex version to 1.17.1

.github/pull_request_template.md
Include DEPENDENCY in PR template
=> Include DEPENDENCY in PR template

CHANGELOG.md, Chart.yaml, README.md
Update cortex to v1.18.1
**Checklist**
=> Bump Cortex version to 1.18.1

CHANGELOG.md, Chart.yaml, README.md
What this PR does:
Update cortex to v1.19.0
Checklist
=> Bump Cortex version to 1.19.0
