cortexproject/cortex-helm-chart

templates/ingress.yaml
templates/nginx-config.yaml
templates/nginx-dep.yaml
templates/nginx-svc.yaml
values.yaml

Instances of cortex that have their own frontdoor/proxy can turn off nginx now.
Addresses #29 
Signed-off-by: Ken Haines <ken@kenhaines.net>

Making Nginx optional

---

.gitignore
Chart.lock
templates/alertmanager-dep.yaml
templates/configs-dep.yaml
templates/distributor-dep.yaml
templates/ingester-dep.yaml
templates/nginx-dep.yaml
templates/querier-dep.yaml
templates/query-frontend-dep.yaml
templates/ruler-dep.yaml
templates/secret.yaml
templates/table-manager-dep.yaml
values.yaml

There is a need to support cortex configurations that are defined & managed outside of the helm chart. This quick PR adds support for cortex to reference a pre-existing secret for its config.
addresses #30

Supporting externally managed Cortex Config

---

templates/alertmanager-dep.yaml
templates/configs-dep.yaml
templates/querier-dep.yaml
templates/ruler-dep.yaml
templates/table-manager-dep.yaml

The target label is missing on several deployments and it is wrong on the querier deployment.
This simple PR is to have a consistent and correct target label on all deployed components.
Signed-off-by: Thibaut Charry <ttcharry@gmail.com>

Fix target labels

---

values.yaml

In #50, the `config.storage` section in the values.yaml file has been duplicated by mistake.
This causes `helm lint` to fail:
```
helm lint .
==> Linting .
[ERROR] templates/: template: cortex/templates/table-manager-svc.yaml:1:7: executing "cortex/templates/table-manager-svc.yaml" at <ne .Values.config.storage.engine "blocks">: error calling ne: incompatible types for comparison
Error: 1 chart(s) linted, 1 chart(s) failed
```
The `engine` key is moved to the already existing `config.storage` section.
Signed-off-by: Thibaut Charry <ttcharry@gmail.com>

Fix values file duplicate config.storage section

---

templates/store-gateway-statefulset.yaml
templates/store-gateway-svc.yaml
values.yaml

The store gateway utilizes GRPC for data access, however, these ports are missing from the template YAML. This PR corrects that.

add grpc ports to store gateway pods and service

---

README.md
templates/alertmanager-dep.yaml
templates/alertmanager-statefulset.yaml
templates/compactor-statefulset.yaml
templates/ingester-dep.yaml
templates/ingester-statefulset.yaml
templates/nginx-config.yaml
templates/querier-dep.yaml
templates/ruler-dep.yaml
templates/store-gateway-statefulset.yaml
values.yaml

When the Kubernetes cluster isn't using the default "cluster.local" DNS domain, deployments fail. This PR allows the DNS domain to be configurable, leaving "cluster.local" as the default.

Add cluster DNS domain value

---

README.md
templates/alertmanager-servicemonitor.yaml
templates/alertmanager-statefulset.yaml
templates/compactor-servicemonitor.yaml
templates/compactor-svc.yaml
templates/configs-servicemonitor.yaml
templates/distributor-servicemonitor.yaml
templates/ingester-servicemonitor.yaml
templates/querier-servicemonitor.yaml
templates/query-frontend-servicemonitor.yaml
templates/ruler-servicemonitor.yaml
templates/store-gateway-servicemonitor.yaml
templates/table-manager-servicemonitor.yaml

Seeing as this is included by [default in the Loki chart](https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml#L203) - I figure this might not be too opinionated of an addition.
I updated the docs as well
edit:  I discovered a alertmanager clustering bug (in the replicas code) that I also fixed

Service Monitors and Compactor Service

---

templates/nginx-config.yaml

- One occurrence of hard-coded "cluster.local" changed to clusterDomain
Signed-off-by: Drew Bowering <Drew.Bowering@epl.ca>

fix: nginx config using non-default clusterDomain

---

values.yaml

Corrects #79 by defaulting the enabled settings for the service monitor to disabled.

Adding default settings for service monitor to each component.

---

values.yaml

Adding a default value for chunk storage to the schema configs. This section needs to be defined even when using the newer block storage format. Resolves #73

Adding default chunk entry to schema configs

---

templates/ingester-svc.yaml
values.yaml

Memberlist discovery can be configured using DNS. This commit changes the ingester service to headless, so memberlist can properly build the ring.

Change the ingester service to headless

---

CHANGELOG.md
templates/alertmanager-svc-headless.yaml

currently, the headless service for the alertmanager is deployed in all configurations. However, it is only needed when the alert manager is a stateful set.

deploy alertmanager headless service when StatefulSet is used

---

Chart.yaml

The repository was deleted, and users that ran "helm dependency update" before Nov 13 2020 don't see any issues. Still, new users cannot download Memcache from googleapis.com and need to change the repository URL to https://charts.helm.sh/stable to run the deployment. 
this fix issues https://github.com/cortexproject/cortex-helm-chart/issues/98

"kubernetes-charts.storage.googleapis.com" is deprecated

---

CHANGELOG.md
README.md
templates/nginx-config.yaml
values.yaml

- Adds new remote write API to nginx. 
- `/api/v1/push`
- API ref: https://cortexmetrics.io/docs/api/#remote-write
- Adds new query frontend APIs to nginx
- `/prometheus/api/v1/label/.*`
- `^/prometheus/api/v1/(read|metadata|labels|series|query_range|query)`
- API ref: https://cortexmetrics.io/docs/api/#querier--query-frontend

Expose new HTTP API paths for remote-write and Query frontend to nginx

---

values.yaml

Latest stable is 1.6, but values still contained 1.4

updating default image tag for cortex

---

Chart.lock
Chart.yaml
ct.yaml
values.yaml

Replace the stable/memcached subcharts with bitnami/memcached. This chart is currently the supported memcached deployment method and allows setting labels on ServiceMonitors bundled with the chart.

issue #124: switch memcached chart to bitnami helm repo

---

CHANGELOG.md
templates/distributor-svc-headless.yaml

Create headless service for distributor to allow GRPC load balancing when using HTTP over GRPC for communicating with distributor.

Add headless service for distributor

---

CHANGELOG.md
templates/alertmanager-dep.yaml

This PR fixes `priorityClassName` in alertmanager deployment.

Fix alertmanager priorityClassName

---

CHANGELOG.md
templates/alertmanager-statefulset.yaml
values.yaml

Based on some deprecations in the [release notes for 1.9](https://github.com/cortexproject/cortex/releases/tag/v1.9.0) this should help solve: https://github.com/cortexproject/cortex-helm-chart/issues/153

Cortex 1.9 Adjustments

---

CHANGELOG.md
values.yaml

Fix the label used in pod affinity expression, it was changed in https://github.com/cortexproject/cortex-helm-chart/pull/144
**Checklist**

fix affinity label selector

---

CHANGELOG.md
templates/store-gateway/store-gateway-svc-headless.yaml

Renames store-gateway-svc.yaml to store-gateway-svc-headless.yaml and fixxes the kubernetes service name.
**Checklist**

fix store gateway service name regression introduced in #144

---

CHANGELOG.md
templates/alertmanager/alertmanager-servicemonitor.yaml
templates/compactor/compactor-servicemonitor.yaml
templates/configs/configs-servicemonitor.yaml
templates/distributor/distributor-servicemonitor.yaml
templates/ingester/ingester-servicemonitor.yaml
templates/querier/querier-servicemonitor.yaml
templates/query-frontend/query-frontend-servicemonitor.yaml
templates/ruler/ruler-servicemonitor.yaml
templates/store-gateway/store-gateway-servicemonitor.yaml
templates/table-manager/table-manager-servicemonitor.yaml
values.yaml

Allows you to use the ServiceMonitor's metricRelabelings and relabelings configuration via helm values. For example:
```YAML
serviceMonitor:
enabled: true
relabelings:
- sourceLabels: [__meta_kubernetes_service_label_cluster]
regex: (.*)
replacement: $1
targetLabel: cluster
action: replace
```
**Checklist**

ServiceMonitors: add options to configure metric- and relabelings

---

CHANGELOG.md
Chart.lock
Chart.yaml
README.md
templates/serviceaccount.yaml
values.yaml

* Upgrades memcached helm chart from 5.5.1 to 5.13.0 which adds support
for specifying service account association and creation
* Adds service account value for whether to automount the token
Signed-off-by: Ryan Probus <ryan.probus@appian.com>

Upgrade memcached and add sa token mount value

---

CHANGELOG.md
templates/_helpers.tpl

This fixes the following Error I got on my store-gateway with the latest helm chart (0.6.0)
```
name=metadata-cache msg="failed to resolve addresses for memcached" addresses=dns+cortex-memcached-blocks-metadata.cortex.svc:11211 err="lookup IP addresses \"cortex-memcached-blocks-metadata.cortex.svc\": i/o timeout"
```
The issue is that `cortex-memcached-blocks-metadata.cortex.svc` doesn't work. Either just use the service name (when its in the same namespace) so `cortex-memcached-blocks-metadata` or use the full svc dns record which would be `cortex-memcached-blocks-metadata.cortex.svc.cluster.local`.
```bash
/ # nslookup cortex-memcached-blocks.cortex.svc
Server:		172.20.0.10
Address:	172.20.0.10:53
** server can't find cortex-memcached-blocks.cortex.svc: NXDOMAIN …
```

Fix wrong memcached addresses

---

CHANGELOG.md
README.md
templates/ingester/ingester-dep.yaml
templates/ingester/ingester-hpa.yaml
templates/ingester/ingester-statefulset.yaml
values.yaml

Adds a `HorizontalPodAutoscaler` for the ingesters.
https://cortexmetrics.io/docs/guides/capacity-planning/ describes that ingester memory grows as series are added, so this autoscaler tracks memory usage to make scaling decisions.
https://cortexmetrics.io/docs/guides/ingesters-scaling-up-and-down/#scaling-down says that "adding more ingesters to a Cortex cluster is considered a safe operation", so this autoscaler behavior is configured to allow adding one ingester pod at a time, but does not automatically scale down.
**Checklist**

add autoscaler for ingesters

---

.github/workflows/lint-test.yml
Makefile
README.md
README.md.gotmpl
values.yaml

I noticed that the README.md had not been completely updated for the 0.6.0 release. This PR adds a PR check to make sure it has been updated.
**Checklist**

check for updated README.md in CI

---

CHANGELOG.md
README.md
ci/test-values.yaml
templates/distributor/distributor-dep.yaml
templates/distributor/distributor-hpa.yaml
values.yaml

Adds a `HorizontalPodAutoscaler` for the distributors.
> Distributors are stateless and can be scaled up and down as needed.
... so this adds the option of automating the scaling.
**Checklist**

add autoscaler for distributors

---

CHANGELOG.md
README.md
ci/test-values.yaml
templates/querier/querier-dep.yaml
templates/querier/querier-hpa.yaml
values.yaml

Adds a `HorizontalPodAutoscaler` for the queriers.
https://cortexmetrics.io/docs/architecture/#querier
> Queriers are stateless and can be scaled up and down as needed.
**Checklist**

add autoscaler for queriers

---

CHANGELOG.md
README.md
templates/ingester/ingester-dep.yaml
templates/ingester/ingester-statefulset.yaml
values.yaml

https://cortexmetrics.io/docs/api/#shutdown says that `/ingester/shutdown` should be called before sending SIGTERM to an ingester. This PR adds a preStop hook to do that. This gives the ingester an opportunity to safely flush blocks from memory before being terminated.
* https://cortexmetrics.io/docs/api/#shutdown
* https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
* https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#lifecycle-v1-core
**Checklist**

graceful shutdown of ingesters

---

CHANGELOG.md
README.md
ci/test-values.yaml
values.yaml

Populate `config.querier.store_gateway_addresses` automatically based on other config
**Checklist**

Populate config.querier.store_gateway_addresses automatically

---

CHANGELOG.md
ci/test-values.yaml
templates/runtime-configmap.yaml

#209 had a whitespace bug in the annotations section. It would eat the whitespace between the `labels:` and `annotations:`. Here's an example of the problem:
```yaml
% helm template . -f ci/test-values.yaml -s templates/runtime-configmap.yaml --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /Users/thayward/go/src/github.com/cortexproject/cortex-helm-chart
---
apiVersion: v1
kind: ConfigMap
metadata:
name: RELEASE-NAME-cortex-runtime-config
namespace: default
labels:
helm.sh/chart: cortex-0.6.0
app.kubernetes.io/name: cortex
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/version: "v1.9.0"
app.kubernetes.io/managed-by: Helmannotations:
foo: bar
data:
runtime_config.yaml: |
{}
Error: YAML parse error on …
```

fix runtimeconfigmap annotations

---

CHANGELOG.md
README.md
templates/nginx/nginx-config.yaml
templates/nginx/nginx-dep.yaml
values.yaml

This commit adds the ability to include an `auth_basic` and
`auth_basic_user_file` directive in the Nginx configuration file.
Fixes #205 
**Checklist**

Add basic auth configuration options to Nginx

---

.github/workflows/lint-test.yml
.github/workflows/readme.yml

This adds a Github Action workflow to automate running `make` (`helm-docs`) on each PR and committing any changes.
This is a continuation of the work in #183.
Github Actions workflows will not trigger on commits pushed by Github Actions (differentiated by the auto auth token), so this workflow will cause the Lint and Test workflow to not run. Since that is a required workflow, the PR cannot be merged until Lint and Test is triggered some other way, like closing and reopening the PR. I've left this PR in draft mode while we try to find the best solution to automate running `make` without defeating the required PR status checks.
Fixes #187

add workflow to generate README.md

---

CHANGELOG.md
README.md
ci/test-values.yaml
templates/nginx/nginx-config.yaml
values.yaml

There are a lot of use cases for nginx and not all of them are supported by the chart. This change allows adding custom configuration to nginx, so that users can implement what they need with nginx without a change to the chart.
**Checklist**

Support customizing the nginx config with values

---

CHANGELOG.md
templates/ingester/ingester-statefulset.yaml

- Brought setting of containerSecurityContext for the Ingester statefulset inline with other components configuration
- Removes the hardcoded value for containerSecurityContext in the ingester statefulset
- Brough the configuration of the ingester containerSecurityContext inline with what is documented in the values.
Didn't raise an issue

- Fixed hardcoding of containerSecurityContext in Ingester statefulset

---

CHANGELOG.md
templates/nginx/nginx-hpa.yaml
templates/nginx/nginx-poddisruptionbudget.yaml

Skip nginx resources if `nginx.enabled` is false. I noticed that the chart was creating an nginx pod disruption budget even though I had set `nginx.enabled` to `false`.
**Checklist**

Don't create nginx resources unless nginx is enabled.

---

CHANGELOG.md
README.md
values.yaml

The cortex docs recommend enabling the bucket index for both the querier
and the store-gateway: https://cortexmetrics.io/docs/blocks-storage/production-tips/.
Any reason not to enable this by default?
**Checklist**

Enable bucket index by default.

---

CHANGELOG.md
README.md
templates/ingester/ingester-dep.yaml
templates/ingester/ingester-statefulset.yaml
values.yaml

Based on cortex docs at
https://cortexmetrics.io/docs/guides/running-cortex-on-kubernetes/#take-extra-care-with-ingesters,
liveness probes for ingesters are not recommended: "We do not recommend
configuring a liveness probe on ingesters - killing them is a last resort and
should not be left to a machine."
**Checklist**

Disable ingester liveness probes by default.

---

CHANGELOG.md
README.md
templates/alertmanager/alertmanager-dep.yaml
templates/alertmanager/alertmanager-statefulset.yaml
templates/compactor/compactor-statefulset.yaml
templates/configs/configs-dep.yaml
templates/distributor/distributor-dep.yaml
templates/ingester/ingester-dep.yaml
templates/ingester/ingester-statefulset.yaml
templates/nginx/nginx-dep.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml
templates/ruler/ruler-dep.yaml
templates/store-gateway/store-gateway-statefulset.yaml
templates/table-manager/table-manager-dep.yaml
values.yaml

Different cortex components might require different cloud provider
permissions. When using gke workload identity, pod iam permissions are
managed by kubernetes service account. This patch allows operators to
use different service accounts for each deployment or statefulset to
support fine-grained control of iam permissions in this scenario.
Fixes #251
**Checklist**

Optionally set service account per dep/statefulset.

---

CHANGELOG.md
templates/alertmanager/alertmanager-poddisruptionbudget.yaml
templates/compactor/compactor-poddisruptionbudget.yaml
templates/configs/configs-poddisruptionbudget.yaml
templates/distributor/distributor-poddisruptionbudget.yaml
templates/ingester/ingester-poddisruptionbudget.yaml
templates/nginx/nginx-poddisruptionbudget.yaml
templates/querier/querier-poddisruptionbudget.yaml
templates/query-frontend/query-poddisruptionbudget.yaml
templates/ruler/ruler-poddisruptionbudget.yaml
templates/store-gateway/store-gateway-poddisruptionbudget.yaml
templates/table-manager/table-manager-poddisruptionbudget.yaml

#227 introduced `policy/v1` for PodDisruptionBudgets with a conditional based on `.Capabilities.APIVersions`: https://github.com/cortexproject/cortex-helm-chart/blob/ad6ebfd62c0bce22dab28f7898623edf6f19115e/templates/compactor/compactor-poddisruptionbudget.yaml#L2
By default, `helm template` [populates `.Capabilities.APIVersions` with all API versions known to Kubernetes](https://github.com/helm/helm/blob/5f74c0e17f2c6ec7b6f488969773c61802e3faff/pkg/chartutil/capabilities.go#L38) client-go v1.22. Many CD tools use this to render the template, then naively try to deploy to Kubernetes clusters that don't support `policy/v1`, such as v1.20 (e.g., https://github.com/argoproj/argo-cd/issues/7291). This results in error messages like `no matches for kind …

workaround for .Capabilities.APIVersions

---

templates/_helpers.tpl
templates/alertmanager/alertmanager-poddisruptionbudget.yaml
templates/compactor/compactor-poddisruptionbudget.yaml
templates/configs/configs-poddisruptionbudget.yaml
templates/distributor/distributor-poddisruptionbudget.yaml
templates/ingester/ingester-poddisruptionbudget.yaml
templates/nginx/nginx-poddisruptionbudget.yaml
templates/querier/querier-poddisruptionbudget.yaml
templates/query-frontend/query-poddisruptionbudget.yaml
templates/ruler/ruler-poddisruptionbudget.yaml
templates/store-gateway/store-gateway-poddisruptionbudget.yaml
templates/table-manager/table-manager-poddisruptionbudget.yaml

This refactors the work from #277 so that the API version logic is only implemented once in a helper.
**Checklist**
This is a refactor, no behavioral change, so I did not include it in the change log.

use helper to populate policy api version

---

CHANGELOG.md
README.md
ci/test-configmap-values.yaml
docs/guides/configure_configmap.markdown
templates/_helpers.tpl
templates/alertmanager/alertmanager-dep.yaml
templates/alertmanager/alertmanager-statefulset.yaml
templates/compactor/compactor-statefulset.yaml
templates/configmap.yaml
templates/configs/configs-dep.yaml
templates/distributor/distributor-dep.yaml
templates/ingester/ingester-dep.yaml
templates/ingester/ingester-statefulset.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml
templates/ruler/ruler-dep.yaml
templates/secret.yaml
templates/store-gateway/store-gateway-statefulset.yaml
templates/table-manager/table-manager-dep.yaml
values.yaml

Optionally pass cortex config as configmap.
Note: I only updated the ingestor templates so far, to verify that the approach makes sense. If it does, I'll copy and paste the updated volume to the other templates.
Fixes #235.
**Checklist**

Optionally pass cortex config as configmap.

---

CHANGELOG.md
README.md
templates/configs/configs-dep.yaml
templates/ingester/ingester-dep.yaml
templates/ingester/ingester-statefulset.yaml
templates/querier/querier-dep.yaml
templates/ruler/ruler-dep.yaml
templates/table-manager/table-manager-dep.yaml
values.yaml

Following up on #263, we should disable ingester startup probes by
default, since the cortex docs note that killing ingesters "should not
be left to a machine". I've also noticed restart loops due to the
startup probe when starting ingesters after downtime, when remote
writers have a backlogs of metrics to send.
**Checklist**
cc @logston

Disable ingester startup probe by default.

---

CHANGELOG.md
README.md
values.yaml

Prometheus scrape configs often use the `prometheus.io/port` annotation
to configure targets per pod:
```
- source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
action: replace
regex: ([^:]+)(?::\d+)?;(\d+)
replacement: $1:$2
target_label: __address__
```
This rule only matches when the `prometheus.io/port` annotation is a
port number, and it's not clear to me how the scrape config could be
modified to work with port names. To make the chart compatible with
standard prometheus scrape configs, this patch changes the default port
annotation from port names to port numbers.
The specific issue that I noticed here was that prometheus was scraping the memberlist port on all pods and polluting the logs with many messages like `"unknown message type" msgType=G`. It …

Use port numbers instead of names in prometheus annotations.

---

CHANGELOG.md
README.md
values.yaml

Removes optimization from querier route logic and applies the default values. The values appear to be wrong to begin with and should have been:
```yaml
query_store_after: 6h
query_ingesters_within: 7h
```
but you actually have to calculate them to get decent values which is out of scope for this helm-chart. See [Production Tips](https://cortexmetrics.io/docs/blocks-storage/production-tips/#how-to-estimate--querierquery-store-after) on how to do that.
**Checklist**

rollback optimization from release 1.0.0

---

.github/workflows/lint-test.yml

Prevents the pipeline from running chart testing test for non chart related changes
**Checklist**

don't run ct test when nothing has changed

---

CHANGELOG.md
docs/assets/scripts/copyCode.js
docs/guides/configure_ruler_and_alertmanager_with_configmap.markdown

Context: The documentation on how to setup and run Alertmanager/Ruler is quite difficult to follow and not comprehensive. Many people have been running into issues regarding the sidecar. In fact, I was advised by some folks who contribute regularly to `cortex` to actually avoid using the sidecar. For this reason, I chose to add a guide on how to setup the ruler and alertmanager simply with configmaps which mount onto the container itself.
**What this PR does**: Adds a guide on how to configure cortex alertmanager and ruler using configmaps mounted onto the containers
**Checklist**

Add guide for configuration am and ruler with mounted config maps

---

CHANGELOG.md
Chart.yaml
templates/nginx/nginx-config.yaml

Optionally allows for alertmanager section of nginx.conf to not be included based upon the `alertermanager.enabled` flag.
Fixes #325

Make alertmanager config optional in nginx.conf 

---

CHANGELOG.md
README.md
templates/store-gateway/store-gateway-statefulset.yaml
values.yaml

Signed-off-by: Ankit Mehta <ankit.mehta@appian.com>
Allows one to set PodManagementPolicy on store-gateway Satefulset same as how we can do that for Ingesters in this helm chart.
**Checklist**

Add podManagementPolicy to store gateway statefulset template

---

CHANGELOG.md
README.md
ci/test-deployment-values.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml
templates/query-scheduler/_helpers-query-scheduler.tpl
templates/query-scheduler/query-scheduler-dep.yaml
templates/query-scheduler/query-scheduler-poddisruptionbudget.yaml
templates/query-scheduler/query-scheduler-servicemonitor.yaml
templates/query-scheduler/query-scheduler-svc-headless.yaml
templates/query-scheduler/query-scheduler-svc.yaml
values.yaml

This MR adds the component Query-Scheduler - this makes scaling query frontend easier.
_Reference: [scaling-query-frontend](https://cortexmetrics.io/docs/operations/scaling-query-frontend/#query-scheduler)._
**Checklist**

Feat Query-Scheduler

---

CHANGELOG.md
ci/test-deployment-values.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml

Improve/Fix query-scheduler addresses
**Checklist**

add dns discovery method for query-scheduler address

---

CHANGELOG.md
templates/_helpers.tpl

**What this PR does**: Fixes the mapping between the query-frontend and the memcached created for it. The other memcached instances spun up in this chart use `.Release.Name`.
**Checklist**

Use .Release.Name in frontend.memcached.address to match service

---

CHANGELOG.md
README.md
templates/alertmanager/alertmanager-dep.yaml
templates/compactor/compactor-statefulset.yaml
templates/configs/configs-dep.yaml
templates/distributor/distributor-dep.yaml
templates/ingester/ingester-dep.yaml
templates/nginx/nginx-dep.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml
templates/query-scheduler/query-scheduler-dep.yaml
templates/ruler/ruler-dep.yaml
templates/store-gateway/store-gateway-statefulset.yaml
templates/table-manager/table-manager-dep.yaml
values.yaml

Provide the ability to configure Pod Topology Spread Constraints.
**Checklist**

Add topology spread constrant option

---

CHANGELOG.md
Chart.yaml
README.md
templates/overrides-exporter/_helpers-overrides-exporter.tpl
templates/overrides-exporter/overrides-exporter-dep.yaml
templates/overrides-exporter/overrides-exporter-servicemonitor.yaml
templates/overrides-exporter/overrides-exporter-svc.yaml
values.yaml

Signed-off-by: Taylor Mutch <taylormutch@gmail.com>
Adds opt-in support for deploying the Cortex overrides exporter. I followed the pattern from the `query-scheduler`, and set the exporter to only run 1 pod (since its metrics should only be collected once for the cluster).
Fixes #359 
**Checklist**

Add Overrides-Exporter

---

CHANGELOG.md
templates/query-frontend/query-frontend-dep.yaml

Signed-off-by: Taylor Mutch <taylormutch@gmail.com>
Adjusts the `scheduler-address` in the query-frontend to be the same passed to the querier.
Fixes https://github.com/cortexproject/cortex-helm-chart/issues/363
**Checklist**

Fix query-scheduler address for query-frontend to use correct address

---

CHANGELOG.md
README.md
renovate.json
values.yaml

From the [OmegaVVeapon/kopf-k8s-sidecar](https://github.com/OmegaVVeapon/kopf-k8s-sidecar) repository, the author is recommending us to move back to switch back to the kiwigrid k8s-sidecar:
> The issue with the [kiwigrid k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) hanging is no longer present as of version [1.15.0](https://github.com/kiwigrid/k8s-sidecar/releases/tag/1.15.0).
> The WATCH_CLIENT_TIMEOUT and WATCH_SERVER_TIMEOUT settings that were introduced in this fork to fix the issue, have now been ported there.
> Thus, I advise users of this repo to switch back to the kiwigrid k8s-sidecar at this point.
> Thank you.
This PR aims to move back to the [kiwigrid/k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) image …

move sidecar image back to kiwigrid/k8s-sidecar

---

CHANGELOG.md
templates/nginx/nginx-dep.yaml

**What this PR does**: Fixes extraContainers indentation in nginx-dep
Fixes #373
**Checklist**

Fix indentation for .Values.nginx.extraContainers

---

docs/guides/upgrade-v1.markdown

Remove the `config.ingester.ring.kvstore` values from value files in the [upgrade-v1](https://github.com/cortexproject/cortex-helm-chart/blob/master/docs/guides/upgrade-v1.markdown) guide.
Fixes #393

Fix configuration error in upgrade-v1 guide

---

CHANGELOG.md
README.md
templates/nginx/nginx-config.yaml
values.yaml

Add a toggle to enable/disable access logs in nginx (similar to loki helm chart)
Nothing
**Checklist**

add nginx access log toggle

---

CHANGELOG.md
README.md
templates/store-gateway/store-gateway-hpa.yaml
values.yaml

This PR adds HPA to the store gateways
Fixes #382 (although that is now closed)
**Checklist**
- [ x ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

Add HPA to store gateway

---

CHANGELOG.md
README.md
templates/purger/_helpers-purger.tpl
templates/purger/purger-dep.yaml
templates/purger/purger-servicemonitor.yaml
templates/purger/purger-svc-headless.yaml
templates/purger/purger-svc.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml
templates/ruler/ruler-dep.yaml
templates/table-manager/table-manager-dep.yaml
values.yaml

Signed-off-by: AlexandreRoux <alexandreroux42@protonmail.com>
This PR add the purger service to cortex-helm 
https://cortexmetrics.io/docs/configuration/configuration-file/#purger_config
https://cortexmetrics.io/docs/api/#purger
The purger service is by default `disabled`.
The following services will have the extraArgs container edited with `-purger` :
+ querier
+ query-frontend
+ ruler
+ table-manager
Fixes #145
**How to test**:
```
curl -v -XPOST --header "X-Scope-OrgID: fake" ${PURGER_URI}:${PURGER_FW_PORT}/purger/delete_tenant
curl -v -XGET --header "X-Scope-OrgID: fake" ${PURGER_URI}:${PURGER_FW_PORT}/purger/delete_tenant_status
level=info ts=2022-10-20T15:35:42.437155739Z caller=tenant_deletion_api.go:63 msg="tenant deletion …
```

add purger components to cortex

---

CHANGELOG.md
templates/_helpers.tpl
templates/distributor/distributor-hpa.yaml
templates/ingester/ingester-hpa.yaml
templates/nginx/nginx-hpa.yaml
templates/querier/querier-hpa.yaml
templates/store-gateway/store-gateway-hpa.yaml

What this PR does / why we need it:
Problem: chart-testing is failing for:
"autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2"
https://github.com/cortexproject/cortex-helm-chart/actions/runs/3606103570/jobs/6077123598
Solution: update charts to start using autoscaler/v2
Signed-off-by: guykomari <guykomari@gmail.com>

Start using autoscaling/v2 for HorizontalPodAutoscaler

---

CHANGELOG.md
Chart.lock
Chart.yaml

**What this PR does**: This change adds correct conditions for the memcache dependencies in the Chart.yaml file, and it also updates the Chart.lock file.
This change has been tested against my own test cluster, with both memcache enabled and disabled.
Fixes #426
**Checklist**

Fix memcache dependency condition

---

CHANGELOG.md
README.md
templates/ruler/_helpers-ruler.tpl
templates/ruler/ruler-dep.yaml
templates/ruler/ruler-hpa.yaml
values.yaml

Defines an optional `HorizontalPodAutoscaler` for the ruler.
Requires a config like:
```yaml
config:
ruler:
enable_sharding: true
ring:
kvstore:
store: memberlist
ruler:
autoscaling:
enabled: true
```
as documented in https://cortexmetrics.io/docs/guides/ruler-sharding/.
~Not sure if we should make any of these default or a condition on the HPA. Or maybe~ added a `fail` block to check for these conditions.
In my experience, both memory and CPU scale pretty linearly with ruler load, so I've included both as target metrics for the ruler HPA.
**Checklist**

add autoscaler for the ruler

---

CHANGELOG.md
README.md
templates/svc-memberlist-headless.yaml
values.yaml

This PR allows for changes to the annotations and labels on the memberlist service. I'm looking for this to be added because I want a label to exclude the service from external-dns without our environment.
n/a
**Checklist**

Add annotations and labels to memberlist service

---

CHANGELOG.md
README.md
templates/alertmanager/alertmanager-servicemonitor.yaml
templates/compactor/compactor-servicemonitor.yaml
templates/distributor/distributor-servicemonitor.yaml
templates/ingester/ingester-servicemonitor.yaml
templates/overrides-exporter/overrides-exporter-servicemonitor.yaml
templates/purger/purger-servicemonitor.yaml
templates/querier/querier-servicemonitor.yaml
templates/query-frontend/query-frontend-servicemonitor.yaml
templates/query-scheduler/query-scheduler-servicemonitor.yaml
templates/ruler/ruler-servicemonitor.yaml
templates/store-gateway/store-gateway-servicemonitor.yaml
values.yaml

**What this PR does**: Adds podTargetLabels to the main values.yaml as an option to add to your servicemonitors. This allows pod labels to get added to metrics being collected.
Fixes #437
**Checklist**

Add podTargeLabels to Prometheus ServiceMonitor CRDs

---

CHANGELOG.md
templates/_helpers.tpl

The chart uses `semverCompare` to interpret `.Capabilties.KubeVersion`. `semverCompare` by default will ignore prereleases. A Kubernetes prerelease will still support the newer API versions targeted for that release, so the chart should allow prereleases when doing version comparisons.
Moreover, popular Kubernetes releases such as AWS EKS [improperly] use prerelease annotation in their version strings, like `1.25.8-eks-ec5523e`, so this issue could cause incorrect API versions to be selected on those clusters.
`semverCompare` supports allowing prereleases by adding `-0` to the operand, like `>=1.21-0`.
This PR adds `-0` to the version comparison so that versions that look like prereleases are supported.
References:
* https://semver.org/
* …

Correctly interpret .Capabilities.KubeVersion when it looks like a prerelease

---

.github/stale.yml

Relaxing the stale-bot config so that it takes longer for PRs to be marked stale and dependency updates are never marked stale (these should be manually triaged).
**Checklist**
- `N/A` `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

relax stale bot

---

CHANGELOG.md
templates/alertmanager/alertmanager-servicemonitor.yaml
templates/compactor/compactor-servicemonitor.yaml
templates/distributor/distributor-servicemonitor.yaml
templates/ingester/ingester-servicemonitor.yaml
templates/overrides-exporter/overrides-exporter-servicemonitor.yaml
templates/querier/querier-servicemonitor.yaml
templates/query-frontend/query-frontend-servicemonitor.yaml
templates/query-scheduler/query-scheduler-servicemonitor.yaml
templates/ruler/ruler-servicemonitor.yaml
templates/store-gateway/store-gateway-servicemonitor.yaml

I think we all messed-up a bit in PR #439. I randomly found this. Previously all podTargetLabels are the same as in the `purger`. Must have been a copy pasta error.
CC:
@jmeza-xyz 
@kd7lxl 
**Checklist**

fix podTargetLabels in all Prometheus ServiceMonitor CRDs

---

CHANGELOG.md
README.md
ci/test-configmap-values.yaml
ci/test-deployment-values.yaml
ci/test-sts-values.yaml
docs/guides/getting_started_with_block_storage.markdown
templates/NOTES.txt
templates/compactor/compactor-statefulset.yaml
templates/compactor/compactor-svc.yaml
templates/purger/purger-svc.yaml
templates/querier/querier-dep.yaml
templates/query-frontend/query-frontend-dep.yaml
templates/ruler/ruler-dep.yaml
templates/store-gateway/store-gateway-statefulset.yaml
templates/store-gateway/store-gateway-svc-headless.yaml
templates/store-gateway/store-gateway-svc.yaml
values.yaml

1. Drops non-existent `purger.enable` flag for some components. I think they used to exists for chunk purger.
2. Removed any reference to `config.storage.engine` since `blocks` is the **only** option that is supported. Since there is nothing to configure, it's better to have no option to configure anything.
**Checklist**

🧹 Cleanup removed & legacy chunk config

---

CHANGELOG.md
README.md
templates/compactor/compactor-statefulset.yaml
templates/store-gateway/store-gateway-statefulset.yaml
values.yaml

Removes the default livenessProbe for compactor and storage-gateway. You can still specify a `livenessProbe` if this is desired.
As discussed in #484
Fixes #484
**Checklist**

remove default livenessProbe for compactor and storage-gateway

---

CHANGELOG.md
README.md
templates/nginx/nginx-config.yaml
values.yaml

Add the possibility to configure the protocol for the upstream URLs in the nginx configuration.
When preparing to upgrade to TLS communication we ran into the problem that the nginx upstream URLs are hard-coded to http.
**Checklist**

Add the possibility to configure the upstream protocol in the nginx configuration for the cortex upstream

---

CHANGELOG.md
templates/nginx/nginx-config.yaml

`auth_orgs` was broken because inside the `range` the upstream protocol feature tried to read the variable from local scope when it only exists in global scope.
Demo:
```
% helm template . --set config.auth_enabled=true --set 'nginx.config.auth_orgs={org_name}' > /dev/null
Error: template: cortex/templates/nginx/nginx-dep.yaml:28:28: executing "cortex/templates/nginx/nginx-dep.yaml" at <include (print $.Template.BasePath "/nginx/nginx-config.yaml") .>: error calling include: template: cortex/templates/nginx/nginx-config.yaml:163:36: executing "cortex/templates/nginx/nginx-config.yaml" at <.Values.nginx.config.upstream_protocol>: can't evaluate field Values in type interface {}
Use --debug flag to render out invalid YAML
```
Fixes …

fix: upstream_protocol reference in auth_orgs

---

.github/workflows/lint-test.yml

Bumps github actions so the pipeline can run again. py 3.7 is now deprecated with ubuntu 20.04.
All dependencies were bumped to the version given as the example from the https://github.com/helm/chart-testing-action/tree/v2.6.1?tab=readme-ov-file#example-workflow action.
**Checklist**

Bump github actions dependencies

---

CHANGELOG.md
README.md
values.yaml

Set align_queries_with_step to false as default, since the 'querier.align-querier-with-step' is false in the [official Cortex docs](https://cortexmetrics.io/docs/configuration/configuration-file/#query_range_config:~:text=%5Balign_queries_with_step%3A%20%3Cboolean%3E%20%7C%20default%20%3D%20false%5D) and [Cortex implementation](https://github.com/cortexproject/cortex/blob/5dd107290f615239d3538ecfdfd63781fc476c31/pkg/querier/tripperware/queryrange/query_range_middlewares.go#L53).
Fixes #514
**Checklist**

Set align_queries_with_step to false as default

---

CHANGELOG.md
README.md
templates/alertmanager/alertmanager-statefulset.yaml
templates/compactor/compactor-statefulset.yaml
templates/ingester/ingester-statefulset.yaml
templates/store-gateway/store-gateway-statefulset.yaml
values.yaml

Adds values allowing users to configure the `persistentVolumeClaimRetentionPolicy` on StatefulSets deployed by the chart.
Fixes #516
**Checklist**

Add ability to configure StatefulSet PVC retention policy

---

CHANGELOG.md
README.md
templates/nginx/nginx-config.yaml
values.yaml

Provide an option to override the push endpoint. For the use cases of mirroring or re-routing the requests before hitting the distributors.
Partially provide an option for #520 
**Checklist**
**Additional notes**
Testing:
```
helm template . | grep /push -A2                                                         
location = /api/prom/push {
proxy_pass      http://release-name-cortex-distributor.default.svc.cluster.local:8080$request_uri;
}
--
location = /api/v1/push {
proxy_pass      http://release-name-cortex-distributor.default.svc.cluster.local:8080$request_uri;
}
========
helm template . --set nginx.config.override_push_endpoint=https://example.com:8080 | grep /push -A2
location = /api/prom/push {
proxy_pass …
```

feat(cortex-nginx): optional override push endpoint

---

CHANGELOG.md
README.md
values.yaml

Uses default value for num_tokens in ingester configuration
Fixes #543
**Checklist**

fix: Use default value for num_tokens in ingester configuration

---

CHANGELOG.md
README.md
values.yaml

**What this PR does**: Switches to clusterIP none so that all instances can be discovered.
Fixes #550
**Checklist**

Enable memcached by default and fix discovering instances
